name: Auto-manage Trello Cards

on:
  # Run automatically every 3 days at 9:00 AM UTC
  schedule:
    - cron: '0 9 */3 * *'
  
  # Allow manual execution
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no changes will be made)'
        required: false
        default: 'false'
        type: boolean

jobs:
  auto-manage-cards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run card auto-management
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        DRY_RUN: ${{ github.event.inputs.dry_run }}
      run: |
        python auto_manage_cards.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: auto-manage-logs
        path: |
          *.log
        retention-days: 30
